### ISSUE TITLE
FHDQR package

### ISSUE THREAD

**Issue by echo-monkey** [XiaoouPan/hdsqr#1]
I also want to use the package "FHDQR". But I can't find an appropriate R version to install it. Could you please tell me which version of R do you use?

**Comment by echo-monkey** [comment]
I have solved this problem, thanks!

**Comment by XiaoouPan** [comment]
Sure. I'm using R version 4.0.2 and it works fine.

**Comment by fboehm** [comment]
> I have solved this problem, thanks!

@echo-monkey - can you tell me how you installed FHDQR? I could only find the binaries on Professor Zou's site: http://users.stat.umn.edu/~zouxx019/ftpdir/code/fhdqr/

**Comment by XiaoouPan** [comment]
> > I have solved this problem, thanks!
> 
> @echo-monkey - can you tell me how you installed FHDQR? I could only find the binaries on Professor Zou's site: http://users.stat.umn.edu/~zouxx019/ftpdir/code/fhdqr/

I forgot the details when I installed it, but since it's a binary package, can we just do

install.packages(path_to_file, repos = NULL, type = "source")?

**Comment by fboehm** [comment]
Thank you, @XiaoouPan ! Yes, I think that you're right about installing the binary for the FHDQR package. I had been hoping that the FHDQR source code was available so that I could install FHDQR on a computer running ubuntu linux operating system. It seems that the authors haven't shared the source code.

**Comment by z1x1wowowo** [comment]
啊啊啊啊啊啊 谁能救救我 这个包怎么才能在新版本里安装使用呢
